### ISSUE TITLE
Threat previews

### ISSUE THREAD

**Issue by ThislsAUsername** [ThislsAUsername/DefendPeace#171]
The AI can do it, so why can't the players?
Probably should work as a toggle, so you can keep track of however many enemy threats as you like.

**Comment by ThatIsAUsername** [comment]
Need more info. I think I can guess your intent, but it definitely isn't a clear enough description to stand on its own.

**Comment by ThislsAUsername** [comment]
Hmm. Ok.

When in map mode, hitting cancel on a unit should add that unit to a collection (call it unitThreats?) maintained by the current Commander.
Hitting cancel on a unit that's already in unitThreats should remove it.
Base Commander should listen to UnitDie events and remove the unit from unitThreats at that point (Or make it a weak list? Whatever)

All units in the currently-viewing Commander's unitThreats should be iterated over, and an overlay painted for where they can attack next turn. (it'd be super cool to also count COAbility-modified stats, but it'd be crazy to work that out with our current architecture...)

I feel like the overlay should be team-color; it fits the aesthetic we have going at the moment, and allows for highlighting your *own* unit ranges as well.

Letting the opacity stack could also be reasonable (maybe cap it?), to allow you to distinguish individual units' range overlaps.

**Comment by ThatIsAUsername** [comment]
All right, new complaint: feature requests should generally specify functionality, not implementation. the implementer may realize a different/better way to do it when they get to code time, and should have the freedom to be creative.

More questions: What happens if we select a unit to move (or select an enemy unit to show their movement range) while attack-ranges are up? Do they hide, or just overlap with the move range?
If I perform a game action (move/attack/etc), should that remove the attack-range overlay?
I'm assuming that the attack-range overlay should always be off at the start of a turn.

**Comment by ThislsAUsername** [comment]
I thought it was pretty clear in the first place, so excuse me for being overly detailed :P 

Highlights should stay up while you have a unit selected; that's the whole point of having them be persistent. They should overlap.
No. They're persistent. that's the point. They should only go away when the user says to make them go away, or the unit dies.
Attack-range overlay should stay between turns also; I don't stop worrying about the range of that Rocket just because I started a new turn.

This is almost exactly what I want (there's a cavalier offscreen with his threat area highlighted):
![image](https://user-images.githubusercontent.com/8674241/53677908-0bea6500-3c7d-11e9-8828-097982260ce1.png)
